"""remove_calories_from_menu_items

Revision ID: 06cc9a401fa8
Revises: cbff37d21784
Create Date: 2025-12-29 23:16:45.563199

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '06cc9a401fa8'
down_revision: Union[str, None] = 'cbff37d21784'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###



