"""add_delivery_time_and_calories_to_menu_items

Revision ID: cbff37d21784
Revises: 2fff80d9f191
Create Date: 2025-12-29 22:44:25.208489

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'cbff37d21784'
down_revision: Union[str, None] = '2fff80d9f191'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('delivery_time', sa.Integer(), nullable=True))
    op.add_column('menu_items', sa.Column('calories', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'menu_items', 'restaurants', ['restaurant_id'], ['id'])
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'menu_items', type_='foreignkey')
    op.drop_column('menu_items', 'calories')
    op.drop_column('menu_items', 'delivery_time')
    # ### end Alembic commands ###



