"""add_google_id

Revision ID: e8e08d35c150
Revises: 61e51558f89b
Create Date: 2025-12-10 01:21:33.405574

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'e8e08d35c150'
down_revision: Union[str, None] = '61e51558f89b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_id', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'users', ['google_id'])
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'google_id')
    # ### end Alembic commands ###



